name: "Platform Application Manifest Dispatch"
description: "Dispatches a repository event to update application manifests with Docker image digests"
author: "Jimmie Fulton <jimmie.fulton@gmail.com>"

# Define the inputs for this action
inputs:
  repository:
    description: "The repository name in owner/repo format"
    required: true
  image-name:
    description: "The name of the Docker image"
    required: true
  directory-name:
    description: "Directory name for ./platform repo path /kubernetes/directory-name"
    required: true
  environment:
    description: "The deployment environment (e.g., dev, stage, prod)"
    required: true
    default: "dev"
  digest:
    description: "The Docker image digest to update"
    required: true
  update-manifest-token:
    description: "Token used to update image manifests"
    required: true
  platform-dispatch-url:
    description: "URL to dispatch platform updates to"
    required: true

# Define the outputs for this action
outputs:
  status:
    description: "The status of the dispatch request"
    value: ${{ steps.dispatch.outputs.status }}

# Define the runs configuration
runs:
  using: "composite"
  steps:
    - name: Dispatch Update Image Digest
      id: dispatch
      shell: bash
      run: |
        echo "Triggering Update Image Digest..."
        echo "Repository: ${{ inputs.repository }}"
        echo "Directory Name: ${{ inputs.directory-name }}"
        echo "Image name: ${{ inputs.image-name }}"
        echo "Environment: ${{ inputs.environment }}"
        echo "Image digest: ${{ inputs.digest }}"
        
        # Send the repository dispatch event
        RESPONSE=$(curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ inputs.update-manifest-token }}" \
          ${{ inputs.platform-dispatch-url }} \
          -d "{\"event_type\": \"update-digest\", \"client_payload\": {\"repository\": \"${{ inputs.repository }}\", \"directory_name\": \"${{ inputs.directory-name }}\", \"image_name\": \"${{ inputs.image-name }}\", \"environment_dir\": \"${{ inputs.environment }}\", \"digest\": \"${{ inputs.digest }}\"}}")
        
        STATUS=$(echo "$RESPONSE" | jq '.status')
        MESSAGE=$(echo "$RESPONSE" | jq '.message')
        if [ "$STATUS" -ge 200 ] && [ "$STATUS" -lt 300 ]; then
          echo "status=success" >> $GITHUB_OUTPUT
          echo "Successfully dispatched update digest event"
          echo "$MESSAGE"
        else
          echo "status=failed" >> $GITHUB_OUTPUT
          echo "Failed to dispatch update digest event, status code: $STATUS"
          echo "$MESSAGE"
          exit 1
        fi

# Define the branding for the action in the GitHub Marketplace
branding:
  icon: "refresh-cw"
  color: "blue"

# Sample Github api response
# {
#   "message": "API rate limit exceeded for installation ID 91288596. If you reach out to GitHub Support for help, please include the request ID DCE1:2AC128:500DB9E:15F60B6D:690A0FA7 and timestamp 2025-11-04 14:37:27 UTC. For more on scraping GitHub and how it may affect your rights, please review our Terms of Service (https://docs.github.com/en/site-policy/github-terms/github-terms-of-service)",
#   "documentation_url": "https://docs.github.com/rest/overview/rate-limits-for-the-rest-api",
#   "status": "403"
# }
